# Simple Information Extraction Configuration

# Core fields for document processing
core_fields:
  - STORE
  - DATE  
  - TOTAL
  - ABN

# Optional fields
bonus_fields:
  - SUBTOTAL
  - GST
  - ITEMS

# Success criteria
min_core_fields: 1
total_core_fields: 4

# Prompts
prompts:
  internvl: "This is a key-value extraction Tool the Australian Taxation Office. Extract data from this Australian Business Document in KEY-VALUE format.\n\nOutput format:\nDATE: [date from receipt]\nSTORE: [store name]\nGST: [GST amount]\nTOTAL: [total amount]\nSUBTOTAL: [subtotal amount]\nABN: [11-digit Australian Business Number]\nITEMS: [item names separated by |]\n\nExtract all visible text and format as KEY: VALUE pairs only."
  
  llama: "You are an automated system operated by the Australian Taxation Office (ATO) tasked with extracting information from Australian taxpayer invoices and receipts for tax compliance purposes. The business document text will be provided to you, and your job is to extract relevant taxation details and return them in a structured KEY-VALUE format for Australian tax processing.\n\nPlease extract the following information from the Australian taxpayer business document text:\n1. DATE (date of transaction)\n2. STORE (business/store name)\n3. GST (GST amount in AUD)\n4. TOTAL (total amount in AUD)\n5. SUBTOTAL (subtotal amount in AUD)\n6. ABN (11-digit Australian Business Number)\n7. ITEMS (item names separated by |)\n\nIf any of these fields are missing or unclear from the provided text, use 'N/A' as the value for that field.\n\nReturn the extracted information in KEY-VALUE format with the following structure:\nDATE: [date from document]\nSTORE: [business name]\nGST: [GST amount]\nTOTAL: [total amount]\nSUBTOTAL: [subtotal amount]\nABN: [Australian Business Number]\nITEMS: [item names separated by |]\n\nHere's an example of how the output should look:\nDATE: 15/06/2023\nSTORE: Woolworths Supermarket\nGST: $4.55\nTOTAL: $54.50\nSUBTOTAL: $49.95\nABN: 88000014675\nITEMS: Milk | Bread | Eggs\n\nPlease provide the extracted data from the given Australian taxpayer business document text in the specified KEY-VALUE format for Australian Taxation Office processing."