# Simple Information Extraction Configuration

# Core fields for document processing
core_fields:
  - STORE
  - DATE  
  - TOTAL
  - ABN

# Optional fields
bonus_fields:
  - SUBTOTAL
  - GST
  - ITEMS

# Success criteria
min_core_fields: 3
total_core_fields: 4

# Prompts
prompts:
  internvl: "This is a key-value extraction Tool the Australian Taxation Office. Extract data from this Tax Invoice in KEY-VALUE format.\n\nOutput format:\nDATE: [date from receipt]\nSTORE: [store name]\nGST: [GST amount]\nTOTAL: [total amount]\nSUBTOTAL: [subtotal amount]\nITEMS: [item names separated by |]\n\nExtract all visible text and format as KEY: VALUE pairs only."
  
  llama: "This is a key-value extraction Tool the Australian Taxation Office. Extract data from this Tax Invoice in KEY-VALUE format.\n\nOutput format:\nDATE: [date from receipt]\nSTORE: [store name]\nGST: [GST amount]\nTOTAL: [total amount]\nSUBTOTAL: [subtotal amount]\nITEMS: [item names separated by |]\n\nExtract all visible text and format as KEY: VALUE pairs only."