# Information Extraction Configuration
# This file defines the key-value pairs to extract from taxpayer documents

extraction_fields:
  # Core business fields (required for success criteria)
  core_fields:
    - name: "STORE"
      description: "business name"
      validation_type: "text"
      required: true
      fallback_patterns:
        - "spotlight|woolworths|coles|bunnings|officeworks|kmart|target|harvey norman|jb hi-fi"
    
    - name: "DATE" 
      description: "date in DD/MM/YYYY format"
      validation_type: "australian_date"
      required: true
      fallback_patterns:
        - "\\b(\\d{1,2}[/-]\\d{1,2}[/-]\\d{2,4}|\\d{1,2}\\.\\d{1,2}\\.\\d{2,4})\\b"
    
    - name: "TOTAL"
      description: "total amount in AUD"
      validation_type: "australian_currency"
      required: true
      fallback_patterns:
        - "(\\$\\d+\\.\\d{2}|\\$\\d+|AUD\\s*\\d+\\.\\d{2})"
    
    - name: "ABN"
      description: "11-digit Australian Business Number"
      validation_type: "australian_abn"
      required: true
      validation_rules:
        - "must_be_11_digits"
        - "no_all_zeros"
        - "no_repeating_pattern"
      invalid_values:
        - "N/A"
        - "NA" 
        - "NOT AVAILABLE"
        - "NOT FOUND"
        - "NONE"
        - "-"
        - "UNKNOWN"
        - "NULL"
        - "EMPTY"
        - "NO ABN"
        - "NO NUMBER"
        - "MISSING"
      fallback_patterns:
        - "\\b(\\d{2}\\s*\\d{3}\\s*\\d{3}\\s*\\d{3}|\\d{11})\\b"
        - "(?:ABN|A\\.B\\.N\\.?)\\s*:?\\s*(\\d{2}\\s*\\d{3}\\s*\\d{3}\\s*\\d{3}|\\d{11})"

  # Optional/bonus fields
  bonus_fields:
    - name: "SUBTOTAL"
      description: "subtotal amount"
      validation_type: "australian_currency" 
      required: false
    
    - name: "GST"
      description: "GST amount"
      validation_type: "australian_currency"
      required: false
    
    - name: "ITEMS"
      description: "item names separated by |"
      validation_type: "text_list"
      required: false

# Success criteria configuration
success_criteria:
  # Minimum number of core fields required for successful extraction
  min_core_fields: 3
  # Total core fields available
  total_core_fields: 4

# Prompt generation settings
prompt_settings:
  instruction_prefix: "Extract data from this Australian business document in KEY-VALUE format."
  output_format_header: "Output format:"
  additional_instructions: |
    Use Australian date format (DD/MM/YYYY) and include currency symbols. 
    For any field that cannot be found in the document, return "N/A". 
    Extract all visible text and format as KEY: VALUE pairs only. 
    Stop after completion.

# Expected ABN images (for evaluation purposes)
evaluation:
  expected_abn_images:
    - "image39.png"
    - "image76.png"  
    - "image71.png"