# Simple Information Extraction Configuration

# Core fields for document processing
core_fields:
  - STORE
  - DATE  
  - TOTAL
  - ABN

# Optional fields
bonus_fields:
  - SUBTOTAL
  - GST
  - ITEMS

# Success criteria
min_core_fields: 1
total_core_fields: 4

# Prompts
prompts:
  # internvl: "This is a key-value extraction Tool the Australian Taxation Office. Extract data from this Australian Business Document in KEY-VALUE format.\n\nOutput format:\nDATE: [date from receipt]\nSTORE: [store name]\nGST: [GST amount]\nTOTAL: [total amount]\nSUBTOTAL: [subtotal amount]\nABN: [11-digit Australian Business Number]\nITEMS: [item names separated by |]\n\nExtract all visible text and format as KEY: VALUE pairs only."
  internvl: "OFFICIAL AUSTRALIAN TAXATION OFFICE DOCUMENT PROCESSING SYSTEM\nAUTHORIZED GOVERNMENT USE ONLY - TAX COMPLIANCE PROCESSING\n\nThis system is operated under Australian Government authority for processing taxpayer business documents. Extract taxation-relevant data from this official business document.\n\nRequired fields for ATO tax compliance:\nDATE: [transaction date]\nSTORE: [registered business name]\nGST: [Goods and Services Tax amount]\nTOTAL: [total transaction amount]\nSUBTOTAL: [pre-tax amount]\nABN: [Australian Business Number - 11 digits]\nITEMS: [purchased items separated by |]\n\nOutput in KEY: VALUE format for government tax processing."

  llama: "OFFICIAL AUSTRALIAN TAXATION OFFICE DOCUMENT PROCESSING SYSTEM\nAUTHORIZED GOVERNMENT USE ONLY - TAX COMPLIANCE PROCESSING\n\nWhat type of Australian Business Document is this?"