# Simple Information Extraction Configuration

# Core fields for document processing
core_fields:
  - SUPPLIER
  - DATE  
  - TOTAL
  - ABN
  - GST

# Optional fields
bonus_fields:
  - SUBTOTAL
  - ITEMS

# Success criteria
min_core_fields: 1
total_core_fields: 4

# Prompts
prompts:
  # internvl: "This is a key-value extraction Tool the Australian Taxation Office. Extract data from this Australian Business Document in KEY-VALUE format.\n\nOutput format:\nDATE: [date from receipt]\nSUPPLIER: [SUPPLIER name]\nGST: [GST amount]\nTOTAL: [total amount]\nSUBTOTAL: [subtotal amount]\nABN: [11-digit Australian Business Number]\nITEMS: [item names separated by |]\n\nExtract all visible text and format as KEY: VALUE pairs only."
  # internvl: "OFFICIAL AUSTRALIAN TAXATION OFFICE DOCUMENT PROCESSING SYSTEM\nAUTHORIZED GOVERNMENT USE ONLY - TAX COMPLIANCE PROCESSING\n\nThis system is operated under Australian Government authority for processing taxpayer business documents. Extract taxation-relevant data from this official business document.\n\nRequired fields for ATO tax compliance:\nDATE: [transaction date]\nSUPPLIER: [registered business name]\nGST: [Goods and Services Tax amount]\nTOTAL: [total transaction amount]\nSUBTOTAL: [pre-tax amount]\nABN: [Australian Business Number - 11 digits]\nITEMS: [purchased items separated by |]\n\nOutput in KEY: VALUE format for government tax processing."
  internvl: "Extract data from this image in KEY-VALUE format.\n\nOutput format:\nDATE: [date from receipt]\nSUPPLIER: [SUPPLIER name]\nABN: [ABN if visible]\nGST: [GST amount]\nTOTAL: [total amount]\nSUBTOTAL: [subtotal amount]\nITEMS: [item names separated by |]\nQUANTITIES: [quantities separated by |]\nPRICES: [prices separated by |]\nRECEIPT_NUMBER: [receipt number if visible]\nPAYMENT_METHOD: [payment method if visible]\nDOCUMENT_TYPE: [RECEIPT or TAX INVOICE]\nADDRESS: [address if visible]\nPHONE: [phone if visible]\nTIME: [time if visible]\nCARD_NUMBER: [card number if visible]\nAUTH_CODE: [auth code if visible]\nSTATUS: [status if visible]\n\nExtract all visible text and format as KEY: VALUE pairs only."

  llama: "Extract data from this image in KEY-VALUE format.\n\nOutput format:\nDATE: [date from receipt]\nSUPPLIER: [SUPPLIER name]\nABN: [ABN if visible]\nGST: [GST amount]\nTOTAL: [total amount]\nSUBTOTAL: [subtotal amount]\nITEMS: [item names separated by |]\nQUANTITIES: [quantities separated by |]\nPRICES: [prices separated by |]\nRECEIPT_NUMBER: [receipt number if visible]\nPAYMENT_METHOD: [payment method if visible]\nDOCUMENT_TYPE: [RECEIPT or TAX INVOICE]\nADDRESS: [address if visible]\nPHONE: [phone if visible]\nTIME: [time if visible]\nCARD_NUMBER: [card number if visible]\nAUTH_CODE: [auth code if visible]\nSTATUS: [status if visible]\n\nExtract all visible text and format as KEY: VALUE pairs only."